### ISSUE TITLE
Camera problem

### ISSUE THREAD

**Issue by raiden1983** [Josh015/Alloy#3]
Hi.I have a problem with camera.When i add Alloy shader and set up everythin like you describe i don't have camera preview window when i select my camera.Can you tell me why?I have only one camera in my scene.

**Comment by Josh015** [comment]
Can you post in our unity thread with images of what you're seeing that looks wrong? Be sure to list Unity version, Alloy version (from CHANGELOG), etc.

https://forum.unity.com/threads/alloy-physical-shader-framework-version-3-for-unity-5.305178/page-35
